name: Docker CI - Flask App

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Docker
      uses: docker/setup-buildx-action@v2

    - name: Build Docker image
      run: |
        cd 02-docker/flask-app
        docker build -t flask-app:latest .

    - name: (Optional) Test Docker Image
      run: echo "✅ Build complete. Add tests if needed."